-- MySQL Script generated by MySQL Workbench
-- Wed Feb 15 18:48:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dm_course_v1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dm_course_v1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dm_course_v1` DEFAULT CHARACTER SET utf8 ;
USE `dm_course_v1` ;

-- -----------------------------------------------------
-- Table `dm_course_v1`.`segment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dm_course_v1`.`segment` (
  `Segment` VARCHAR(50) NOT NULL,
  `segment_id` INT NOT NULL,
  PRIMARY KEY (`segment_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dm_course_v1`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dm_course_v1`.`city` (
  `city` VARCHAR(100) NOT NULL,
  `Country_Region` VARCHAR(100) NOT NULL,
  `State` VARCHAR(100) NOT NULL,
  `Region` VARCHAR(100) NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`city_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dm_course_v1`.`adress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dm_course_v1`.`adress` (
  `Postal_Code` INT NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`Postal_Code`),
  INDEX `city_id_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `city_id`
    FOREIGN KEY (`city_id`)
    REFERENCES `dm_course_v1`.`city` (`city_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dm_course_v1`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dm_course_v1`.`customer` (
  `Customer_ID` VARCHAR(45) NOT NULL,
  `Customer_Name` VARCHAR(100) NOT NULL,
  `segment_id` INT NOT NULL,
  `Postal_Code` INT NOT NULL,
  PRIMARY KEY (`Customer_ID`),
  INDEX `segment_id_idx` (`segment_id` ASC) VISIBLE,
  INDEX `Postal Code_idx` (`Postal_Code` ASC) VISIBLE,
  CONSTRAINT `segment_id`
    FOREIGN KEY (`segment_id`)
    REFERENCES `dm_course_v1`.`segment` (`segment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Postal Code`
    FOREIGN KEY (`Postal_Code`)
    REFERENCES `dm_course_v1`.`adress` (`Postal_Code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dm_course_v1`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dm_course_v1`.`order` (
  `Order_ID` VARCHAR(200) NOT NULL,
  `Order_Date` DATE NULL,
  `Ship_Date` DATE NULL,
  `Ship_Mode` VARCHAR(45) NULL,
  `Customer_ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Order_ID`),
  INDEX `Customer ID_idx` (`Customer_ID` ASC) VISIBLE,
  CONSTRAINT `Customer ID`
    FOREIGN KEY (`Customer_ID`)
    REFERENCES `dm_course_v1`.`customer` (`Customer_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dm_course_v1`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dm_course_v1`.`category` (
  `Category` VARCHAR(45) NOT NULL,
  `Sub_Category` VARCHAR(45) NOT NULL,
  `Sub_Category_id` INT NOT NULL,
  PRIMARY KEY (`Sub_Category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dm_course_v1`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dm_course_v1`.`product` (
  `Product_ID` VARCHAR(200) NOT NULL,
  `Product_Name` VARCHAR(200) NOT NULL,
  `sub_category_id` INT NOT NULL,
  PRIMARY KEY (`Product_ID`),
  INDEX `sub_category_id_idx` (`sub_category_id` ASC) VISIBLE,
  CONSTRAINT `sub_category_id`
    FOREIGN KEY (`sub_category_id`)
    REFERENCES `dm_course_v1`.`category` (`Sub_Category_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dm_course_v1`.`product_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dm_course_v1`.`product_order` (
  `Order_ID` VARCHAR(200) NOT NULL,
  `Product_ID` VARCHAR(200) NOT NULL,
  `Sales` FLOAT NOT NULL,
  `Quantity` INT NOT NULL,
  `Discount` FLOAT NOT NULL,
  `Profit` FLOAT NULL,
  `product_order_id` INT NOT NULL,
  PRIMARY KEY (`product_order_id`),
  INDEX `Order ID_idx` (`Order_ID` ASC) VISIBLE,
  INDEX `Product ID_idx` (`Product_ID` ASC) VISIBLE,
  CONSTRAINT `Order ID`
    FOREIGN KEY (`Order_ID`)
    REFERENCES `dm_course_v1`.`order` (`Order_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Product ID`
    FOREIGN KEY (`Product_ID`)
    REFERENCES `dm_course_v1`.`product` (`Product_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
